import { ConflictException, Injectable, UnauthorizedException } from '@nestjs/common'; import { InjectRepository } from '@nestjs/typeorm'; import * as bcrypt from 'bcrypt'; import { Repository } from 'typeorm'; import { JwtService } from '@nestjs/jwt'; import { connect as tlsConnect, TLSSocket } from 'tls'; import { User } from '../../users/infrastructure/user.entity'; import { LoginDto, RegisterDto, RequestOtpDto, VerifyOtpDto } from './auth.dto';
@Injectable() export class AuthService {constructor(@InjectRepository(User) private users:Repository<User>,private jwt:JwtService){}
 async register(dto:RegisterDto){if(await this.users.findOneBy({email:dto.email.toLowerCase()}))throw new ConflictException('این ایمیل قبلاً ثبت شده است'); const user=await this.users.save(this.users.create({email:dto.email.toLowerCase(),fullName:dto.fullName,role:'customer',passwordHash:null}));return this.issue(user)}
 async requestOtp(dto:RequestOtpDto){const email=dto.email.toLowerCase();let user=await this.users.findOneBy({email});if(!user){user=await this.users.save(this.users.create({email,fullName:dto.fullName||'مشتری برنامه وفاداری',role:'customer',passwordHash:null}))}const code=Math.floor(10000+Math.random()*90000).toString();user.otpHash=await bcrypt.hash(code,10);user.otpExpiresAt=new Date(Date.now()+5*60*1000);user.otpAttempts=0;await this.users.save(user);await this.sendOtpEmail(email,code);return {message:'کد پنج‌رقمی ورود به ایمیل شما ارسال شد.',expiresInSeconds:300,...(process.env.NODE_ENV==='production'?{}:{devOtp:code})}}
 async verifyOtp(dto:VerifyOtpDto){const user=await this.users.findOneBy({email:dto.email.toLowerCase()});if(!user||!user.otpHash||!user.otpExpiresAt||user.otpExpiresAt<new Date())throw new UnauthorizedException('کد ورود منقضی یا نامعتبر است');if(user.otpAttempts>=5)throw new UnauthorizedException('تعداد تلاش‌ها بیش از حد مجاز است');const ok=await bcrypt.compare(dto.code,user.otpHash);if(!ok){user.otpAttempts+=1;await this.users.save(user);throw new UnauthorizedException('کد ورود نادرست است')}user.otpHash=null;user.otpExpiresAt=null;user.otpAttempts=0;await this.users.save(user);return this.issue(user)}
 async login(dto:LoginDto){return this.verifyOtp(dto)} issue(user:User){const {passwordHash,otpHash,otpExpiresAt,otpAttempts,...safe}=user;return {accessToken:this.jwt.sign({sub:user.id,role:user.role,email:user.email}),user:safe}} async me(id:string){const user=await this.users.findOneByOrFail({id});const {passwordHash,otpHash,otpExpiresAt,otpAttempts,...safe}=user;return safe}
 private async sendOtpEmail(to:string,code:string){const host=process.env.SMTP_HOST,user=process.env.SMTP_USER,password=process.env.SMTP_PASSWORD,from=process.env.SMTP_FROM;if(!host||!user||!password||!from){console.log(`[gift-shop otp] ${to}: ${code}`);return}const port=Number(process.env.SMTP_PORT||465),secure=process.env.SMTP_SECURE!=='false';if(!secure)throw new Error('SMTP_SECURE=false is not supported by the built-in OTP mailer yet');const subject='کد ورود فروشگاه هدیه';const text=`کد پنج‌رقمی ورود شما: ${code}\nاین کد تا ۵ دقیقه معتبر است.`;const html=`<div dir="rtl" style="font-family:Tahoma,Arial,sans-serif;line-height:1.9;color:#071A2C"><h2>کد ورود فروشگاه هدیه</h2><p>کد پنج‌رقمی ورود شما:</p><p style="font-size:32px;font-weight:700;letter-spacing:6px;direction:ltr">${code}</p><p>این کد تا ۵ دقیقه معتبر است.</p></div>`;await this.sendSmtp({host,port,servername:process.env.SMTP_TLS_SERVERNAME||host,user,password,from,to,subject,text,html})}
 private async sendSmtp(m:{host:string;port:number;servername:string;user:string;password:string;from:string;to:string;subject:string;text:string;html:string}){const socket=await new Promise<TLSSocket>((resolve,reject)=>{const s=tlsConnect({host:m.host,port:m.port,servername:m.servername},()=>resolve(s));s.setTimeout(15000);s.once('error',reject);s.once('timeout',()=>reject(new Error('SMTP connection timed out')))});let buffer='';const read=()=>new Promise<string>((resolve,reject)=>{const onData=(chunk:Buffer)=>{buffer+=chunk.toString('utf8');const lines=buffer.split(/\r?\n/).filter(Boolean);const last=lines.at(-1);if(last&&/^\d{3} /.test(last)){socket.off('data',onData);socket.off('error',onError);const out=buffer;buffer='';resolve(out)}};const onError=(error:Error)=>{socket.off('data',onData);reject(error)};socket.on('data',onData);socket.once('error',onError)});const write=async(command:string,ok:number[],redact=false)=>{socket.write(command+'\r\n');const response=await read();const code=Number(response.slice(0,3));if(!ok.includes(code))throw new Error(`SMTP command failed: ${code}${redact?'':` ${response.trim()}`}`);return response};try{await read();await write(`EHLO ${m.servername}`,[250]);try{const plain=Buffer.from(`\u0000${m.user}\u0000${m.password}`).toString('base64');await write(`AUTH PLAIN ${plain}`,[235],true)}catch{await write('AUTH LOGIN',[334]);await write(Buffer.from(m.user).toString('base64'),[334],true);await write(Buffer.from(m.password).toString('base64'),[235],true)}await write(`MAIL FROM:<${this.extractEmail(m.from)}>`,[250]);await write(`RCPT TO:<${m.to}>`,[250,251]);await write('DATA',[354]);socket.write(this.buildMessage(m)+'\r\n.\r\n');const dataResponse=await read();if(![250].includes(Number(dataResponse.slice(0,3))))throw new Error('SMTP DATA failed');await write('QUIT',[221]);}finally{socket.end()}}
 private buildMessage(m:{from:string;to:string;subject:string;text:string;html:string}){const boundary='gift-shop-otp-'+Date.now();const subject=this.mimeWord(m.subject);const from=this.formatAddress(m.from);const text=m.text.replace(/^\./gm,'..');const html=m.html.replace(/^\./gm,'..');return [`From: ${from}`,`To: <${m.to}>`,`Subject: ${subject}`,'MIME-Version: 1.0',`Content-Type: multipart/alternative; boundary="${boundary}"`,'',`--${boundary}`,'Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: 8bit','',text,`--${boundary}`,'Content-Type: text/html; charset=UTF-8','Content-Transfer-Encoding: 8bit','',html,`--${boundary}--`].join('\r\n')}
 private mimeWord(value:string){return `=?UTF-8?B?${Buffer.from(value,'utf8').toString('base64')}?=`}
 private extractEmail(value:string){return value.match(/<([^>]+)>/)?.[1]||value}
 private formatAddress(value:string){const match=value.match(/^(.+?)\\s*<([^>]+)>$/);return match?`${this.mimeWord(match[1].replace(/^["']|["']$/g,''))} <${match[2]}>`:`<${value}>`}
}
